### PR TITLE
Fix ResultMapper on ordered tuple

### LINKED ISSUE #806: ResultMapper.tuple fails with complex types
This fails:

```scala
  it should "derive a tuple composed of more complex types" in {
    val mapper = ResultMapper.tuple[Option[Int], Either[String, Boolean], List[Int], Map[String, String], Option[Set[Long]]]

    val input = NeoMap(
      properties = Map(
        "opt" -> Value.Integer(5),
        "either" -> Value.Bool(true),
        "list" -> Value.ListValue(List(Value.Integer(0), Value.Integer(10))),
        "map" -> NeoMap(Map("foo" -> Value.Str("bar"), "baz" -> Value.Str("quax"))),
        "none" -> Value.NullValue // it does not fail without this last one
      )
    )
    val result = mapper.decode(input)

    result.value shouldBe (Some(5), Right(true), List(0, 10), Map("foo" -> "bar", "baz" -> "quax"), None)
  }
```

All elements of the tuple are mixed up, because calling `values` to iterate over them calls `properties.valuesIterator.toList`, `properties` being a `Map` that does not keep entries order.

The easiest (but maybe not the right one?) way to fix this is to use a `SeqMap` for `NeoMap.properties` to keep the order of values in the Map, or introduce a distinct:

```scala
/** Represents a Neo4j heterogeneous ordered tuple */
final case class Tuple(properties: SeqMap[String, NeoType]) extends NeoObject
```

### PR DESCRIPTION
**Pull request by turb**
Fixes #806 

Two commits:
- create failing tests
- one possible fix using a `SeqMap`

### CODE REVIEW

File: tests/src/test/scala/neotypes/generic/DeriveTupleMapSpec.scala [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+      )
+    )
+    val result = mapper.decode(input)
+
+    result.value shouldBe (Some(5), Right(true), List(0, 10), Map("foo" -> "bar", "baz" -> "quax"), None)
+  }
+
+  it should "not derive an instance for an untagged HList" in {
+    assertDoesNotCompile("import shapeless._; ResultMapper.tuple[Int :: String :: HNil]")
+  }
```
Comment (BalmungSan) [inline tests/src/test/scala/neotypes/generic/DeriveTupleMapSpec.scala:49]: This is unnecessary :)

**Review by BalmungSan — APPROVED** [review]
Thanks a lot!

File: tests/src/test/scala/neotypes/generic/DeriveTupleMapSpec.scala (hunk 1 above)
Comment (turb) [reply tests/src/test/scala/neotypes/generic/DeriveTupleMapSpec.scala]: Fixup 427ad34dcb334d07ea0bc1ef86628d65e743b9d0

**Review by BalmungSan — APPROVED** [review]
